name: flutter_grpc_mock
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_grpc_common:
    path: ../grpc/client
  hooks_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  json_annotation: ^4.8.0
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  grpc: ^3.1.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_lint: ^1.1.6
  riverpod_generator: ^2.1.4
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
